api_version = "2025-01"

[[extensions]]
name = "VIP Beläge Discount"
handle = "vip-belage-discount"

uid = "227e23c7-0613-00c6-5884-fdd179a907cccc0d67fb"
type = "product_discounts"

[extensions.build]
command = "npm run build"
path = "dist/function.wasm"
watch = ["src/**/*.{js,ts}"]

[extensions.input.variables]
namespace = "vip-belage-discount"
key = "percentage"
