name = "VIP Beläge Discount"
client_id = ""
application_url = "https://{{ HOST }}"
embedded = false

[access_scopes]
scopes = "read_discounts,write_discounts"

[auth]
redirect_urls = [
  "https://{{ HOST }}/auth/callback"
]

[webhooks]
api_version = "2025-01"

[pos]
embedded = false
