api_version = "unstable"

[[extensions]]
name = "t:name"
handle = "best-discount-allocator"
type = "function"
uid = "2c38e670-5400-b194-0ab4-63066e8448fabcf7dc84"
description = "t:description"

  [[extensions.targeting]]
  target = "purchase.discounts-allocator.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
